CLASS zbp_c_custom_tableprod DEFINITION
  public
  abstract
  final
  for behavior of ZC_CUSTOM_TABLEPROD .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_C_CUSTOM_TABLEPROD IMPLEMENTATION.
ENDCLASS.
