CLASS zbp_c_matdistlinebrd DEFINITION
  public
  abstract
  final
  for behavior of ZC_MATDISTLINEBRD .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_C_MATDISTLINEBRD IMPLEMENTATION.
ENDCLASS.
